; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32cam]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_rts = 0
monitor_dtr = 0
monitor_filters = esp32_exception_decoder
build_unflags =
	-DARDUINO_USB_MODE=0
	-DARDUINO_USB_CDC_ON_BOOT=0
build_flags =
	-DBOARD_HAS_PSRAM
	-DCORE_DEBUG_LEVEL=0
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-iquote include
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.flash_size = 8MB
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
lib_deps =
	bblanchon/ArduinoJson@^7.4.2
	adafruit/Adafruit NeoPixel@^1.12.4
board_build.embed_files =
	data/jsqr.min.js.gz
	data/nacl.min.js.gz
