using CamPortal.Components;
using CamPortal.Extensions;
using CamPortal.Infrastructure.Data;
using CamPortal.MapperConfiguration;
using Microsoft.AspNetCore.Server.Kestrel.Core;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

builder.Configuration.AddUserSecrets<Program>();

var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
builder.Services.AddDbContextFactory<CamPortalDBContext>(options =>
options.UseSqlServer(connectionString));

builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();

builder.Services.AddControllers();

builder.Services.AddAutoMapper(builder =>
{
    builder.AddProfile<MapperProfile>();
});

var certificatePassword = builder.Configuration.GetSection("CertificatesConfig")["CertificateAutoGeneratedPassword"];

//if an exception occurs becasue no certificate is found you have to run the dedicated "CertGenerator" app
//port 7010 (HTTPS) is the device-facing endpoint used with certificate pinning and must stay bound in every environment
//port 5120 (HTTP) is the browser-facing endpoint that nginx terminates TLS for and proxies to
builder.WebHost.ConfigureKestrel(options =>
{
    options.ListenAnyIP(7010, listenOptions =>
    {
        listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
        listenOptions.UseHttps("server.pfx", certificatePassword);
    });
    options.ListenAnyIP(5120, listenOptions =>
    {
        listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
    });
});

builder.Services.AddServices();
builder.Services.AddForwardedHeaders(builder.Configuration);
builder.Services.AddRateLimiterPolicy();
builder.Services.AddAuth();

builder.Logging.ClearProviders();
builder.Logging.AddConsole();
builder.Logging.AddDatabaseLogging();

var app = builder.Build();

app.ApplyMigrations(app.Services);

await app.SeedInitialAdminAsync();

await app.RecoverPendingVideoExportsAsync();

app.UseForwardedHeaders();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

if (app.Environment.IsDevelopment())
{
    app.UseHttpsRedirection();
}

app.UseStaticFiles();

app.UseRouting();

app.UseRateLimiter();

app.UseAuthentication();

app.UseAuthorization();

app.UseAntiforgery();

app.MapStaticAssets();

app.MapRazorComponents<App>().AddInteractiveServerRenderMode();

app.MapControllers();

app.Run();
