using BlazorCamPortal.Components;
using BlazorCamPortal.Extensions;
using BlazorCamPortal.Infrastructure.Data;
using BlazorCamPortal.MapperConfiguration;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
builder.Services.AddDbContext<CamPortalDBContext>(options =>
options.UseSqlServer(connectionString));

builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();

builder.Services.AddControllers();

builder.Services.AddAutoMapper(builder =>
{
    builder.AddProfile<MapperProfile>();
});

if (builder.Environment.IsDevelopment())
{
    builder.Configuration.AddUserSecrets<Program>();
}

var certificatePassword = builder.Configuration.GetSection("CertificatesConfig")["CertificateAutoGeneratedPassword"];

//if an exception occurs becasue no certificate is found you have to run the dedicated "CertGenerator" app
builder.WebHost.ConfigureKestrel(options =>
{
    options.ListenAnyIP(7010, listenOptions =>
    {
        listenOptions.UseHttps("server.pfx", certificatePassword);
    });
    options.ListenAnyIP(5120);
});

builder.Services.AddServices();
builder.Services.AddRepositories();

var app = builder.Build();

app.ApplyMigrations(app.Services);

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseAntiforgery();

app.MapStaticAssets();
app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode();

app.MapControllers();

app.Run();
