using CamPortal.Components;
using CamPortal.Extensions;
using CamPortal.Infrastructure.Data;
using CamPortal.MapperConfiguration;
using Microsoft.AspNetCore.Server.Kestrel.Core;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
builder.Services.AddDbContextFactory<CamPortalDBContext>(options =>
options.UseSqlServer(connectionString));

builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();

builder.Services.AddControllers();

builder.Services.AddAutoMapper(builder =>
{
    builder.AddProfile<MapperProfile>();
});

if (builder.Environment.IsDevelopment())
{
    builder.Configuration.AddUserSecrets<Program>();
}

var certificatePassword = builder.Configuration.GetSection("CertificatesConfig")["CertificateAutoGeneratedPassword"];

//if an exception occurs becasue no certificate is found you have to run the dedicated "CertGenerator" app
builder.WebHost.ConfigureKestrel(options =>
{
    options.ListenAnyIP(7010, listenOptions =>
    {
        listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
        listenOptions.UseHttps("server.pfx", certificatePassword);
    });
    options.ListenAnyIP(5120, listenOptions =>
    {
        listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
    });
});

builder.Services.AddServices();
builder.Services.AddRepositories();
builder.Services.AddRateLimiterPolicy();
builder.Services.AddAuth();

builder.Logging.ClearProviders();
builder.Logging.AddConsole();
builder.Logging.AddDatabaseLogging();

var app = builder.Build();

app.ApplyMigrations(app.Services);

await app.SeedInitialAdminAsync();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseRouting();

app.UseRateLimiter();

app.UseAuthentication();

app.UseAuthorization();

app.UseAntiforgery();

app.MapStaticAssets();

app.MapRazorComponents<App>().AddInteractiveServerRenderMode();

app.MapControllers();

app.Run();
