// <auto-generated />
using System;
using CamPortal.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CamPortal.Infrastructure.Migrations
{
    [DbContext(typeof(CamPortalDBContext))]
    partial class CamPortalDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.CameraConfiguration", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Brightness")
                        .HasColumnType("real");

                    b.Property<int>("CameraAspectRatio")
                        .HasColumnType("int");

                    b.Property<bool>("CaseSensorInstalled")
                        .HasColumnType("bit");

                    b.Property<float>("Contrast")
                        .HasColumnType("real");

                    b.Property<int>("FlipMode")
                        .HasColumnType("int");

                    b.Property<float>("FrameRotation")
                        .HasColumnType("real");

                    b.Property<double>("MovementThresholdOffset")
                        .HasColumnType("float");

                    b.Property<int>("ResolutionHeight")
                        .HasColumnType("int");

                    b.Property<int>("ResolutionWidth")
                        .HasColumnType("int");

                    b.Property<double>("RotationThresholdOffset")
                        .HasColumnType("float");

                    b.Property<bool>("SecurityArmed")
                        .HasColumnType("bit");

                    b.Property<float>("SharpenFactor")
                        .HasColumnType("real");

                    b.Property<float>("ZoomFactor")
                        .HasColumnType("real");

                    b.Property<int>("ZoomStartX")
                        .HasColumnType("int");

                    b.Property<int>("ZoomStartY")
                        .HasColumnType("int");

                    b.HasKey("DeviceId");

                    b.ToTable("CameraConfigurations");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.CameraTelemetry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvgCaptureMs")
                        .HasColumnType("int");

                    b.Property<int>("AvgEncryptMs")
                        .HasColumnType("int");

                    b.Property<int>("AvgFrameKB")
                        .HasColumnType("int");

                    b.Property<int>("AvgSendMs")
                        .HasColumnType("int");

                    b.Property<int>("BufferReadyPercent")
                        .HasColumnType("int");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CaptureFailures")
                        .HasColumnType("bigint");

                    b.Property<bool>("CaseOpen")
                        .HasColumnType("bit");

                    b.Property<double>("DewPointC")
                        .HasColumnType("float");

                    b.Property<long>("FailedSends")
                        .HasColumnType("bigint");

                    b.Property<double>("Fps")
                        .HasColumnType("float");

                    b.Property<long>("FrameCount")
                        .HasColumnType("bigint");

                    b.Property<double>("HumidityPercent")
                        .HasColumnType("float");

                    b.Property<bool>("IsNight")
                        .HasColumnType("bit");

                    b.Property<bool>("LightSensorPresent")
                        .HasColumnType("bit");

                    b.Property<int>("LightSensorValue")
                        .HasColumnType("int");

                    b.Property<int>("MaxCaptureMs")
                        .HasColumnType("int");

                    b.Property<int>("MaxEncryptMs")
                        .HasColumnType("int");

                    b.Property<int>("MaxFrameKB")
                        .HasColumnType("int");

                    b.Property<int>("MaxSendMs")
                        .HasColumnType("int");

                    b.Property<bool>("MotionActive")
                        .HasColumnType("bit");

                    b.Property<int>("MotionEvents")
                        .HasColumnType("int");

                    b.Property<bool>("MotionSensorPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("TempHumiditySensorPresent")
                        .HasColumnType("bit");

                    b.Property<double>("TemperatureC")
                        .HasColumnType("float");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CameraId", "TimestampUtc");

                    b.ToTable("CameraTelemetry");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ipv4Address")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PairStatus")
                        .HasColumnType("int");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("SessionToken")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("SessionTokenExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("PairStatus");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.DeviceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeviceCategory")
                        .HasColumnType("int");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("IconUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.ExportedVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExportFinishedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExportStartedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExportStatus")
                        .HasColumnType("int");

                    b.Property<string>("ExportedURLForDownload")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("SizeInMB")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VideoEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VideoStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("ExportFinishedDate");

                    b.HasIndex("UserId");

                    b.ToTable("ExportedVideos");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.LogMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Exception")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LogLevel")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("TimestampUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUTC");

                    b.ToTable("LogMessages");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.PreprovisionAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClaimedFromIpv4")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExpectedNetworkIpv4")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ExpectedSubnetMask")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreprovisionStatus")
                        .HasColumnType("int");

                    b.Property<int>("RemainingAttempts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "PreprovisionStatus");

                    b.ToTable("PreprovisionAttempts");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7acd488-f9d9-4026-8b59-3da8637b9e90"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("2686070a-a062-48c9-aafe-de74e5c65376"),
                            Name = "User"
                        },
                        new
                        {
                            Id = new Guid("60ed5d3e-f4d6-456b-8748-47f9bf9c7c53"),
                            Name = "InfoDashboard"
                        });
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.SmokeAlarmDetectorConfiguration", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("MinBatterySOCForAlert")
                        .HasColumnType("float");

                    b.HasKey("DeviceId");

                    b.ToTable("SmokeAlarmDetectorConfigurations");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.SmokeAlarmTelemetry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BatterySOCPercent")
                        .HasColumnType("float");

                    b.Property<double>("BatteryVoltage")
                        .HasColumnType("float");

                    b.Property<int>("BootCount")
                        .HasColumnType("int");

                    b.Property<int>("DetectedAlarmBeepCount")
                        .HasColumnType("int");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Event")
                        .HasColumnType("int");

                    b.Property<bool>("IsCharging")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LoggedTimeUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("LoggedTimeUTC");

                    b.ToTable("SmokeAlarmTelemetry");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.SystemSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CameraChunkRetention")
                        .HasColumnType("int");

                    b.Property<int>("EncodedVideoRetention")
                        .HasColumnType("int");

                    b.Property<double>("SecurityMaxHumidityPercent")
                        .HasColumnType("float");

                    b.Property<double>("SecurityMaxTemperatureC")
                        .HasColumnType("float");

                    b.Property<int>("SecurityMinFps")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f4d2a1c-0b6e-4c3a-9d57-1f2e3a4b5c6d"),
                            CameraChunkRetention = 3,
                            EncodedVideoRetention = 5,
                            SecurityMaxHumidityPercent = 70.0,
                            SecurityMaxTemperatureC = 90.0,
                            SecurityMinFps = 4
                        });
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsFirstTimeSetup")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("SecurityStamp")
                        .HasMaxLength(1000)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SecurityStamp")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.UserCameraPositionLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LayoutType")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("UserId", "CameraId")
                        .IsUnique();

                    b.ToTable("UserCameraLayouts");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsersRoles");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfCamerasPerRowForLiveGrid")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.VideoChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChunkEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ChunkStartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("SizeInMB")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("VideoChunks");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.CameraConfiguration", b =>
                {
                    b.HasOne("CamPortal.Infrastructure.Data.Entities.Device", "Device")
                        .WithOne("CameraConfiguration")
                        .HasForeignKey("CamPortal.Infrastructure.Data.Entities.CameraConfiguration", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.CameraTelemetry", b =>
                {
                    b.HasOne("CamPortal.Infrastructure.Data.Entities.Device", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.Device", b =>
                {
                    b.HasOne("CamPortal.Infrastructure.Data.Entities.DeviceType", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.ExportedVideo", b =>
                {
                    b.HasOne("CamPortal.Infrastructure.Data.Entities.Device", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CamPortal.Infrastructure.Data.Entities.User", "User")
                        .WithMany("ExportedVideos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.PreprovisionAttempt", b =>
                {
                    b.HasOne("CamPortal.Infrastructure.Data.Entities.Device", "Device")
                        .WithMany("PreprovisionAttempts")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.SmokeAlarmDetectorConfiguration", b =>
                {
                    b.HasOne("CamPortal.Infrastructure.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.SmokeAlarmTelemetry", b =>
                {
                    b.HasOne("CamPortal.Infrastructure.Data.Entities.Device", "Device")
                        .WithMany("SmokeAlarmTelemetries")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.UserCameraPositionLayout", b =>
                {
                    b.HasOne("CamPortal.Infrastructure.Data.Entities.Device", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CamPortal.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.UserRole", b =>
                {
                    b.HasOne("CamPortal.Infrastructure.Data.Entities.Role", "Role")
                        .WithMany("RoleUsers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CamPortal.Infrastructure.Data.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.UserSettings", b =>
                {
                    b.HasOne("CamPortal.Infrastructure.Data.Entities.User", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("CamPortal.Infrastructure.Data.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.VideoChunk", b =>
                {
                    b.HasOne("CamPortal.Infrastructure.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.Device", b =>
                {
                    b.Navigation("CameraConfiguration");

                    b.Navigation("PreprovisionAttempts");

                    b.Navigation("SmokeAlarmTelemetries");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.Role", b =>
                {
                    b.Navigation("RoleUsers");
                });

            modelBuilder.Entity("CamPortal.Infrastructure.Data.Entities.User", b =>
                {
                    b.Navigation("ExportedVideos");

                    b.Navigation("UserRoles");

                    b.Navigation("UserSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
