#pragma once

#define FIRMWARE_VERSION "1.0.0"

#define RESET_BUTTON_PIN 27
#define RESET_BUTTON_HOLD_MS 5000

#define RGB_LED_PIN 14
#define RGB_LED_COUNT 1

#define STATUS_LED_PIN 13
#define STATUS_LED_BLINK_INTERVAL_MS 400

#define TEMPERATURE_SENSOR_PIN 25
#define TEMPERATURE_RESOLUTION_BITS 12
#define TEMPERATURE_CONVERSION_MS 800
#define TEMPERATURE_INTERVAL_MS 2000
#define TEMPERATURE_INVALID_RAW 0x8000

#define FAN_RELAY_PIN 33
#define FAN_RELAY_ACTIVE_LEVEL LOW
#define FAN_RELAY_IDLE_LEVEL HIGH

#define FAN_TACH_PIN 32
#define FAN_TACH_SAMPLE_MS 1000
#define FAN_TACH_PULSES_PER_REVOLUTION 2

#define DOOR_M1_IN1_PIN 19
#define DOOR_M1_IN2_PIN 18
#define DOOR_M1_IN3_PIN 5
#define DOOR_M1_IN4_PIN 17

#define DOOR_M2_IN1_PIN 15
#define DOOR_M2_IN2_PIN 2
#define DOOR_M2_IN3_PIN 4
#define DOOR_M2_IN4_PIN 16

#define DOOR_LIMIT_SWITCH_PIN 26
#define DOOR_OPEN_STEPS 3970
#define DOOR_MAX_CLOSE_STEPS 6000
#define DOOR_OPEN_MAX_SPEED 600
#define DOOR_OPEN_ACCELERATION 300
#define DOOR_CLOSE_MAX_SPEED 250
#define DOOR_CLOSE_ACCELERATION 100

#define NVS_NAMESPACE "settings"

#define WIFI_CONNECT_TIMEOUT_MS 20000

#define PREPROVISION_RETRY_DELAY_MS 30000
#define CHANNEL_RETRY_DELAY_MS 10000
#define CHANNEL_MAX_ATTEMPTS 3
#define LOCAL_RETRY_INTERVAL_MS 60000

// Thresholds the vent falls back to when the server cannot be reached.
#define LOCAL_START_TEMPERATURE_C 30.0f
#define LOCAL_STOP_TEMPERATURE_C 23.0f

#define PROVISION_AP_SSID_PREFIX "AutoVent-Setup-"
#define PROVISION_AP_PASSWORD "ventsetup1234"
#define PROVISION_AP_CHANNEL 6
#define PROVISION_AP_HIDDEN false
#define PROVISION_AP_MAX_CLIENTS 4
#define PROVISION_HTTP_PORT 80

// must match the server, do not change per device
#define DOMAIN_TAG "campr-provision-v1"
#define DATA_CHANNEL_DOMAIN_TAG "CAMPR-STREAM-V1"
#define DATA_CHANNEL_HKDF_INFO "CAMPR-STREAM-V1-derived"

#define DATA_CHANNEL_BUFFER_SIZE 4096
#define DATA_CHANNEL_HANDSHAKE_TIMEOUT_MS 10000
#define DATA_CHANNEL_SEND_TIMEOUT_MS 5000
#define DATA_CHANNEL_MAX_SESSION_MESSAGES 4000000000ULL
#define DATA_CHANNEL_MAX_SESSION_DURATION_MS (120UL * 60UL * 1000UL)
#define DATA_CHANNEL_MAX_MESSAGE_SIZE 256

#define DEVICE_COMMAND_VERSION 1
#define VENT_PAYLOAD_VERSION 1
#define VENT_REPORT_INTERVAL_MS 5000

#define ServerHttpsPort 7010
#define ServerTcpPort 7000

#define DEBUG_ON false

#define DEBUG_PRINT(x)   \
  do                     \
  {                      \
    if (DEBUG_ON)        \
      Serial.println(x); \
  } while (0)
