#include "provision_ap.h"
#include "config.h"
#include <ArduinoJson.h>
#include <DNSServer.h>
#include <WebServer.h>
#include <WiFi.h>
#include <esp_random.h>
#include <mbedtls/base64.h>

extern "C"
{
#include "tweetnacl.h"
}

extern "C" void randombytes(unsigned char *buf, unsigned long long len)
{
  esp_fill_random(buf, (size_t)len);
}

extern const uint8_t jsqr_gz_start[] asm("_binary_data_jsqr_min_js_gz_start");
extern const uint8_t jsqr_gz_end[] asm("_binary_data_jsqr_min_js_gz_end");
extern const uint8_t nacl_gz_start[] asm("_binary_data_nacl_min_js_gz_start");
extern const uint8_t nacl_gz_end[] asm("_binary_data_nacl_min_js_gz_end");

namespace provision_ap
{
  static WebServer _server(PROVISION_HTTP_PORT);
  static DNSServer _dns;
  static bool _running = false;
  static volatile bool _hasCreds = false;
  static DeviceCredentials _pendingCreds;
  static String _apSsid;

  static constexpr size_t NACL_PUBLICKEY_LEN = 32;
  static constexpr size_t NACL_SECRETKEY_LEN = 32;
  static constexpr size_t NACL_NONCE_LEN = 24;
  static constexpr size_t NACL_BOXZERO_LEN = 16;
  static constexpr size_t NACL_ZERO_LEN = 32;

  static uint8_t _devicePublicKey[NACL_PUBLICKEY_LEN];
  static uint8_t _deviceSecretKey[NACL_SECRETKEY_LEN];
  static bool _keypairReady = false;

  static const IPAddress AP_IP(192, 168, 4, 1);
  static const IPAddress AP_GATEWAY(192, 168, 4, 1);
  static const IPAddress AP_NETMASK(255, 255, 255, 0);

  static const char LANDING_PAGE_HTML[] PROGMEM = R"HTML(<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">
<title>CamPortal Setup</title>
<style>
:root{color-scheme:dark;--bg:#0b1220;--card:#161d2c;--accent:#7dd3fc;--accent2:#22d3ee;--ok:#34d399;--err:#f87171;--muted:#9ca3af;--text:#e6edf3;}
*{box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,system-ui,Segoe UI,Roboto,sans-serif;margin:0;padding:16px;background:var(--bg);color:var(--text);min-height:100vh}
.card{max-width:520px;margin:24px auto;background:var(--card);border-radius:14px;padding:22px;box-shadow:0 10px 30px rgba(0,0,0,.45)}
h1{margin:0 0 4px;color:var(--accent);font-size:22px}
.sub{color:var(--muted);font-size:13px;margin-bottom:18px}
.btn{display:flex;align-items:center;justify-content:center;gap:8px;width:100%;border:0;border-radius:10px;padding:14px 16px;font-size:16px;font-weight:600;cursor:pointer;transition:transform .05s ease}
.btn:active{transform:scale(.98)}
.btn-primary{background:linear-gradient(135deg,var(--accent),var(--accent2));color:#06121f}
.btn-ghost{background:transparent;color:var(--text);border:1px solid #2a3450;margin-top:12px}
.btn[disabled]{opacity:.55;cursor:wait}
.hidden{display:none!important}
.section{margin-top:18px;padding-top:18px;border-top:1px solid #232c44}
textarea{width:100%;min-height:96px;background:#0e1626;color:var(--text);border:1px solid #2a3450;border-radius:10px;padding:12px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;resize:vertical}
label{display:block;font-size:13px;color:var(--muted);margin-bottom:6px}
.status{margin-top:14px;padding:12px;border-radius:10px;font-size:14px;display:none}
.status.show{display:block}
.status.info{background:#0e1626;border:1px solid #2a3450;color:#bfd1ff}
.status.ok{background:#06251a;border:1px solid #134e3a;color:var(--ok)}
.status.err{background:#2a1212;border:1px solid #5b1f1f;color:var(--err)}
.spinner{width:16px;height:16px;border:2px solid rgba(255,255,255,.4);border-top-color:#06121f;border-radius:50%;animation:spin .8s linear infinite}
@keyframes spin{to{transform:rotate(360deg)}}
.tiny{font-size:11px;color:var(--muted);margin-top:10px;text-align:center}
.hint{margin-top:14px;padding:12px;border-radius:10px;background:#0e1626;border:1px solid #2a3450;font-size:12px;color:var(--muted);line-height:1.55}
.hint b{color:var(--text)}
.hint code{background:#1a233a;color:var(--accent);padding:1px 6px;border-radius:6px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
</style>
</head><body>
<div class="card">
<h1>CamPortal device setup</h1>
<div class="sub">Provide the credentials generated by the wizard. The device will reboot and join your Wi-Fi automatically.</div>

<button id="scanBtn" class="btn btn-primary">
  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><path d="M14 14h3v3h-3zM20 14v3M14 20h6M17 20v1"/></svg>
  Scan QR with camera
</button>
<input id="qrFile" type="file" accept="image/*" capture="environment" class="hidden">

<div id="status" class="status"></div>

<div id="cnaHint" class="hint hidden">
  <b>Camera didn't open?</b> Your phone may be showing this page inside its Wi-Fi sign-in helper, which blocks the camera.<br>
  <b>iOS:</b> tap <i>Cancel</i> &rarr; <i>Use Without Internet</i>, then open <b>Safari</b> and visit <code>http://192.168.4.1</code>.<br>
  <b>Android:</b> swipe down, tap the Wi-Fi notification &rarr; <i>Use as is</i> (or dismiss), then open <b>Chrome</b> and visit <code>http://192.168.4.1</code>.
</div>

<div class="section">
  <label>Or paste the credentials URL from the wizard</label>
  <textarea id="manualInput" placeholder="http://192.168.4.1/provision?d=..."></textarea>
  <button id="manualBtn" class="btn btn-ghost">Send credentials</button>
</div>

<div class="tiny">Open this page on your phone after joining the device's setup Wi-Fi.</div>
</div>

<script src="/jsqr.js"></script>
<script src="/nacl.js"></script>
<script>
(function(){
  var scanBtn = document.getElementById('scanBtn');
  var qrFile  = document.getElementById('qrFile');
  var status  = document.getElementById('status');
  var manualBtn = document.getElementById('manualBtn');
  var manualInput = document.getElementById('manualInput');
  var cnaHint = document.getElementById('cnaHint');
  var cnaWatcher = null;
  function showCnaHint(){ cnaHint.classList.remove('hidden'); }

  function setStatus(kind, msg){
    status.className = 'status show ' + kind;
    status.textContent = msg;
  }
  function clearStatus(){ status.className = 'status'; status.textContent = ''; }

  function extractD(text){
    if(!text) return null;
    text = text.trim();
    var m = text.match(/[?&]d=([^&\s]+)/);
    if(m) return m[1];
    if(/^[A-Za-z0-9_\-]+$/.test(text)) return text;
    return null;
  }

  function b64ToBytes(b64){
    var bin = atob(b64.replace(/-/g,'+').replace(/_/g,'/'));
    var out = new Uint8Array(bin.length);
    for(var i=0;i<bin.length;i++){ out[i] = bin.charCodeAt(i); }
    return out;
  }
  function bytesToB64(bytes){
    var bin = '';
    for(var i=0;i<bytes.length;i++){ bin += String.fromCharCode(bytes[i]); }
    return btoa(bin);
  }

  function submit(d){
    setStatus('info', 'Securing and sending credentials...');
    scanBtn.disabled = true; manualBtn.disabled = true;
    if(typeof nacl !== 'object' || !nacl.box){
      setStatus('err', 'Encryption library failed to load. Reload the page and try again.');
      scanBtn.disabled = false; manualBtn.disabled = false;
      return;
    }
    fetch('/devicekey', { cache: 'no-store' })
      .then(function(r){ if(!r.ok){ throw new Error('device key HTTP ' + r.status); } return r.text(); })
      .then(function(pkText){
        var devicePub = b64ToBytes(pkText.trim());
        if(devicePub.length !== 32){ throw new Error('bad device key'); }
        var eph = nacl.box.keyPair();
        var nonce = nacl.randomBytes(24);
        var msg = new TextEncoder().encode(d);
        var box = nacl.box(msg, nonce, devicePub, eph.secretKey);
        var body = JSON.stringify({
          epk: bytesToB64(eph.publicKey),
          nonce: bytesToB64(nonce),
          box: bytesToB64(box)
        });
        return fetch('/provision', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          cache: 'no-store',
          body: body
        });
      })
      .then(function(r){
        if(r.ok){
          setStatus('ok', 'Credentials accepted. The device is rebooting and will join your Wi-Fi.');
        } else {
          throw new Error('HTTP ' + r.status);
        }
      })
      .catch(function(e){
        setStatus('err', 'Failed to send credentials: ' + (e.message || e));
        scanBtn.disabled = false; manualBtn.disabled = false;
      });
  }

  function decodeImage(file){
    return new Promise(function(resolve, reject){
      if(!file){ reject(new Error('No image selected')); return; }
      var url = URL.createObjectURL(file);
      var img = new Image();
      img.onload = function(){
        try {
          var max = 1600;
          var w = img.naturalWidth, h = img.naturalHeight;
          if(w > max || h > max){
            var s = max / Math.max(w, h);
            w = Math.round(w * s); h = Math.round(h * s);
          }
          var c = document.createElement('canvas');
          c.width = w; c.height = h;
          var ctx = c.getContext('2d');
          ctx.drawImage(img, 0, 0, w, h);
          URL.revokeObjectURL(url);
          var data = ctx.getImageData(0, 0, w, h);
          if(typeof jsQR !== 'function'){ reject(new Error('Decoder not loaded')); return; }
          var code = jsQR(data.data, data.width, data.height, { inversionAttempts: 'attemptBoth' });
          if(!code){ reject(new Error('No QR detected in image')); return; }
          resolve(code.data);
        } catch(err){
          URL.revokeObjectURL(url);
          reject(err);
        }
      };
      img.onerror = function(){ URL.revokeObjectURL(url); reject(new Error('Could not read image')); };
      img.src = url;
    });
  }

  scanBtn.addEventListener('click', function(){
    if(cnaWatcher){ clearTimeout(cnaWatcher); }
    cnaWatcher = setTimeout(showCnaHint, 1500);
    qrFile.click();
  });

  document.addEventListener('visibilitychange', function(){
    if(document.visibilityState === 'hidden' && cnaWatcher){
      clearTimeout(cnaWatcher); cnaWatcher = null;
    }
  });

  qrFile.addEventListener('change', function(){
    if(cnaWatcher){ clearTimeout(cnaWatcher); cnaWatcher = null; }
    var file = qrFile.files && qrFile.files[0];
    qrFile.value = '';
    if(!file) return;
    clearStatus();
    setStatus('info', 'Decoding QR...');
    decodeImage(file).then(function(text){
      var d = extractD(text);
      if(!d){ setStatus('err', 'Decoded QR is not a CamPortal setup code.'); return; }
      submit(d);
    }).catch(function(err){
      setStatus('err', err.message || String(err));
    });
  });

  manualBtn.addEventListener('click', function(){
    var d = extractD(manualInput.value);
    if(!d){ setStatus('err', 'Paste the full setup URL from the wizard.'); return; }
    submit(d);
  });
})();
</script>
</body></html>)HTML";

  static String buildApSsid()
  {
    uint8_t mac[6];
    WiFi.macAddress(mac);
    char buf[40];
    snprintf(buf, sizeof(buf), "%s%02X%02X", PROVISION_AP_SSID_PREFIX, mac[4], mac[5]);
    return String(buf);
  }

  static bool urlSafeBase64Decode(const String &input, String &out)
  {
    String b64 = input;
    b64.replace('-', '+');
    b64.replace('_', '/');
    while (b64.length() % 4 != 0)
    {
      b64 += '=';
    }

    size_t outCap = (b64.length() / 4) * 3 + 4;
    uint8_t *buf = (uint8_t *)malloc(outCap);
    if (buf == nullptr)
    {
      return false;
    }

    size_t outLen = 0;
    int ret = mbedtls_base64_decode(buf, outCap, &outLen,
                                    (const unsigned char *)b64.c_str(), b64.length());
    if (ret != 0)
    {
      free(buf);
      return false;
    }

    out = "";
    out.reserve(outLen + 1);
    for (size_t i = 0; i < outLen; i++)
    {
      out += (char)buf[i];
    }
    free(buf);
    return true;
  }

  static String base64Encode(const uint8_t *data, size_t len)
  {
    size_t cap = ((len + 2) / 3) * 4 + 1;
    uint8_t *buf = (uint8_t *)malloc(cap);
    if (buf == nullptr)
    {
      return String();
    }
    size_t outLen = 0;
    if (mbedtls_base64_encode(buf, cap, &outLen, data, len) != 0)
    {
      free(buf);
      return String();
    }
    buf[outLen] = '\0';
    String result((const char *)buf);
    free(buf);
    return result;
  }

  static bool generateDeviceKeypair()
  {
    if (crypto_box_keypair(_devicePublicKey, _deviceSecretKey) != 0)
    {
      return false;
    }
    _keypairReady = true;
    return true;
  }

  static bool decryptProvisionPayload(const String &body, String &payloadOut)
  {
    if (!_keypairReady)
    {
      return false;
    }

    JsonDocument doc;
    if (deserializeJson(doc, body))
    {
      return false;
    }

    String epkB64 = doc["epk"].as<String>();
    String nonceB64 = doc["nonce"].as<String>();
    String boxB64 = doc["box"].as<String>();
    if (epkB64.length() == 0 || nonceB64.length() == 0 || boxB64.length() == 0)
    {
      return false;
    }

    uint8_t epk[NACL_PUBLICKEY_LEN];
    uint8_t nonce[NACL_NONCE_LEN];
    String epkRaw, nonceRaw;
    if (!urlSafeBase64Decode(epkB64, epkRaw) || epkRaw.length() != NACL_PUBLICKEY_LEN ||
        !urlSafeBase64Decode(nonceB64, nonceRaw) || nonceRaw.length() != NACL_NONCE_LEN)
    {
      return false;
    }
    memcpy(epk, epkRaw.c_str(), NACL_PUBLICKEY_LEN);
    memcpy(nonce, nonceRaw.c_str(), NACL_NONCE_LEN);

    String boxRaw;
    if (!urlSafeBase64Decode(boxB64, boxRaw) || boxRaw.length() < NACL_BOXZERO_LEN)
    {
      return false;
    }

    size_t cipherLen = NACL_BOXZERO_LEN + boxRaw.length();
    uint8_t *cipher = (uint8_t *)malloc(cipherLen);
    uint8_t *plain = (uint8_t *)malloc(cipherLen);
    if (cipher == nullptr || plain == nullptr)
    {
      free(cipher);
      free(plain);
      return false;
    }

    memset(cipher, 0, NACL_BOXZERO_LEN);
    memcpy(cipher + NACL_BOXZERO_LEN, boxRaw.c_str(), boxRaw.length());

    int ret = crypto_box_open(plain, cipher, cipherLen, nonce, epk, _deviceSecretKey);
    free(cipher);
    if (ret != 0)
    {
      free(plain);
      return false;
    }

    size_t payloadLen = cipherLen - NACL_ZERO_LEN;
    payloadOut = "";
    payloadOut.reserve(payloadLen + 1);
    for (size_t i = 0; i < payloadLen; i++)
    {
      payloadOut += (char)plain[NACL_ZERO_LEN + i];
    }
    free(plain);
    return true;
  }

  static bool parseProvisionJson(const String &json, DeviceCredentials &out)
  {
    JsonDocument doc;
    DeserializationError err = deserializeJson(doc, json);
    if (err)
    {
      DEBUG_PRINT(String("Provision JSON parse error: ") + err.c_str());
      return false;
    }

    out.wifiSsid = doc["WifiSSID"].as<String>();
    out.wifiPass = doc["WifiPassword"].as<String>();
    out.deviceId = doc["DeviceId"].as<String>();
    out.privateKey = doc["PrivateKey"].as<String>();
    out.nonce = doc["Nonce"].as<String>();
    out.serverIp = doc["ServerIp"].as<String>();
    out.serverIdentityPubKey = doc["ServerIdentityPublicKey"].as<String>();

    return out.wifiSsid.length() > 0 &&
           out.deviceId.length() > 0 &&
           out.privateKey.length() > 0 &&
           out.nonce.length() > 0 &&
           out.serverIp.length() > 0 &&
           out.serverIdentityPubKey.length() > 0;
  }

  static void handleProvision()
  {
    if (_hasCreds)
    {
      _server.send(200, "text/plain", "Credentials already received");
      return;
    }

    if (!_server.hasArg("plain"))
    {
      _server.send(400, "text/plain", "Missing body");
      return;
    }

    String data;
    if (!decryptProvisionPayload(_server.arg("plain"), data))
    {
      DEBUG_PRINT("Provisioning payload decryption failed");
      _server.send(400, "text/plain", "Decryption failed");
      return;
    }

    String json;
    if (!urlSafeBase64Decode(data, json))
    {
      _server.send(400, "text/plain", "Invalid encoding");
      return;
    }

    DeviceCredentials parsed;
    if (!parseProvisionJson(json, parsed))
    {
      _server.send(400, "text/plain", "Incomplete payload");
      return;
    }

    _pendingCreds = parsed;
    _hasCreds = true;

    DEBUG_PRINT("Provisioning payload accepted; device will reboot to STA mode.");
    _server.send(200, "text/plain", "Credentials accepted; device rebooting.");
  }

  static void handleDeviceKey()
  {
    if (!_keypairReady)
    {
      _server.send(503, "text/plain", "Device key not ready");
      return;
    }
    _server.sendHeader("Cache-Control", "no-store");
    _server.send(200, "text/plain", base64Encode(_devicePublicKey, NACL_PUBLICKEY_LEN));
  }

  static void handleNaclJs()
  {
    size_t len = nacl_gz_end - nacl_gz_start;
    _server.sendHeader("Content-Encoding", "gzip");
    _server.sendHeader("Cache-Control", "max-age=86400");
    _server.setContentLength(len);
    _server.send(200, "application/javascript", "");
    _server.client().write(nacl_gz_start, len);
  }

  static void handleRoot()
  {
    _server.sendHeader("Cache-Control", "no-store");
    _server.send_P(200, "text/html", LANDING_PAGE_HTML);
  }

  static void handleAppleSuccess()
  {
    static const char body[] = "<HTML><HEAD><TITLE>Success</TITLE></HEAD><BODY>Success</BODY></HTML>";
    _server.send(200, "text/html", body);
  }

  static void handleAndroidNoPortal()
  {
    _server.send(204, "text/plain", "");
  }

  static void handleWindowsConnectTest()
  {
    _server.send(200, "text/plain", "Microsoft Connect Test");
  }

  static void handleWindowsNcsi()
  {
    _server.send(200, "text/plain", "Microsoft NCSI");
  }

  static void handleJsQr()
  {
    size_t len = jsqr_gz_end - jsqr_gz_start;
    _server.sendHeader("Content-Encoding", "gzip");
    _server.sendHeader("Cache-Control", "max-age=86400");
    _server.setContentLength(len);
    _server.send(200, "application/javascript", "");
    _server.client().write(jsqr_gz_start, len);
  }

  static void handleNotFound()
  {
    _server.sendHeader("Location", "/", true);
    _server.send(302, "text/plain", "");
  }

  bool begin()
  {
    if (_running)
    {
      return true;
    }

    _apSsid = buildApSsid();
    WiFi.persistent(false);
    WiFi.mode(WIFI_AP);
    WiFi.softAPConfig(AP_IP, AP_GATEWAY, AP_NETMASK);

    const char *pass = PROVISION_AP_PASSWORD;
    const char *passArg = (pass != nullptr && pass[0] != '\0') ? pass : nullptr;

    bool ok = WiFi.softAP(_apSsid.c_str(), passArg,
                          PROVISION_AP_CHANNEL,
                          PROVISION_AP_HIDDEN ? 1 : 0,
                          PROVISION_AP_MAX_CLIENTS);
    if (!ok)
    {
      DEBUG_PRINT("Failed to start soft AP");
      return false;
    }

    DEBUG_PRINT("Soft AP started: " + _apSsid + " @ " + WiFi.softAPIP().toString());

    if (!generateDeviceKeypair())
    {
      DEBUG_PRINT("Failed to generate provisioning keypair");
      WiFi.softAPdisconnect(true);
      WiFi.mode(WIFI_OFF);
      return false;
    }

    _dns.setErrorReplyCode(DNSReplyCode::NoError);
    _dns.start(53, "*", AP_IP);

    _server.on("/provision", HTTP_POST, handleProvision);
    _server.on("/devicekey", HTTP_GET, handleDeviceKey);
    _server.on("/jsqr.js", HTTP_GET, handleJsQr);
    _server.on("/nacl.js", HTTP_GET, handleNaclJs);
    _server.on("/", HTTP_GET, handleRoot);
    _server.on("/generate_204", HTTP_GET, handleAndroidNoPortal);
    _server.on("/gen_204", HTTP_GET, handleAndroidNoPortal);
    _server.on("/hotspot-detect.html", HTTP_GET, handleAppleSuccess);
    _server.on("/library/test/success.html", HTTP_GET, handleAppleSuccess);
    _server.on("/success.txt", HTTP_GET, handleAppleSuccess);
    _server.on("/connecttest.txt", HTTP_GET, handleWindowsConnectTest);
    _server.on("/ncsi.txt", HTTP_GET, handleWindowsNcsi);
    _server.onNotFound(handleNotFound);
    _server.begin();

    _hasCreds = false;
    _running = true;
    return true;
  }

  TickResult tick(DeviceCredentials &credentialsOut)
  {
    if (!_running)
    {
      return IDLE;
    }

    _dns.processNextRequest();
    _server.handleClient();

    if (_hasCreds)
    {
      credentialsOut = _pendingCreds;
      _hasCreds = false;
      return RECEIVED;
    }
    return IDLE;
  }

  bool clientConnected()
  {
    return _running && WiFi.softAPgetStationNum() > 0;
  }

  void end()
  {
    if (!_running)
    {
      return;
    }
    _server.stop();
    _dns.stop();
    WiFi.softAPdisconnect(true);
    WiFi.mode(WIFI_OFF);
    _running = false;
    memset(_deviceSecretKey, 0, sizeof(_deviceSecretKey));
    _keypairReady = false;
    DEBUG_PRINT("Soft AP stopped");
  }

  String apSsid()
  {
    return _apSsid;
  }
}
