#pragma once

#define FIRMWARE_VERSION "2.0.0"

#define DOMAIN_TAG "campr-provision-v1"

#define CAMERA_RESOLUTION FRAMESIZE_QXGA

#define RESET_BUTTON_PIN 14
#define RESET_BUTTON_HOLD_MS 5000

#define RGB_LED_PIN 48
#define RGB_LED_COUNT 1

#define STATUS_LED_PIN 21
#define STATUS_LED_BLINK_INTERVAL_MS 400

#define LIGHT_SENSOR_PIN 1
#define LIGHT_SENSOR_SAMPLE_INTERVAL_MS 1000
#define LIGHT_SENSOR_NIGHT_THRESHOLD 350
#define LIGHT_SENSOR_DAY_THRESHOLD 500
#define LIGHT_SENSOR_PRESENCE_DELTA 2800

#define IR_CUT_IN1_PIN 41
#define IR_CUT_IN2_PIN 42
#define IR_CUT_PULSE_MS 250
#define IR_CUT_FORCE_BLACK_AND_WHITE false

#define IR_CUT_TEST_MODE false
#define IR_CUT_TEST_INTERVAL_MS 3000

#define I2C_SDA_PIN 38
#define I2C_SCL_PIN 39
#define I2C_CLOCK_HZ 400000

// temperature and humidity sensor
#define SHT3X_I2C_ADDR 0x44
#define SHT3X_SAMPLE_INTERVAL_MS 2000

// accelerometer and gyroscope sensor
#define MPU6050_I2C_ADDR 0x68
#define MPU6050_SAMPLE_INTERVAL_MS 10
#define MOTION_MOVE_G 0.12f
#define MOTION_IMPACT_G 2.5f
#define MOTION_FREEFALL_G 0.45f
#define MOTION_FREEFALL_MS 100
#define MOTION_ROTATE_DPS 45.0f
#define MOTION_WARMUP_MS 1500

#define CASE_SWITCH_INSTALLED true
#define CASE_SWITCH_PIN 2
#define CASE_SWITCH_DEBOUNCE_MS 50

// alarm buzzer on MX1508 motor B channel (IN3 driven, IN4 tied to GND)
#define BUZZER_PIN 40
#define BUZZER_ON_MS 80
#define BUZZER_OFF_MS 50

#define NVS_NAMESPACE "settings"

#define WIFI_CONNECT_TIMEOUT_MS 20000
#define WIFI_RETRY_DELAY_MS 5000

#define PREPROVISION_RETRY_DELAY_MS 30000
#define STREAM_RETRY_DELAY_MS 10000

#define PROVISION_AP_SSID_PREFIX "CamPortal-Setup-"
#define PROVISION_AP_PASSWORD "campsetup1234"
#define PROVISION_AP_CHANNEL 6
#define PROVISION_AP_HIDDEN false
#define PROVISION_AP_MAX_CLIENTS 4
#define PROVISION_HTTP_PORT 80

#define DATA_CHANNEL_BUFFER_SIZE (1024 * 1024)
#define DATA_CHANNEL_DOMAIN_TAG "CAMPR-STREAM-V1"
#define DATA_CHANNEL_HKDF_INFO "CAMPR-STREAM-V1-derived"
#define DATA_CHANNEL_HANDSHAKE_TIMEOUT_MS 10000
#define DATA_CHANNEL_SEND_TIMEOUT_MS 5000
#define DATA_CHANNEL_MAX_SESSION_MESSAGES 4000000000ULL
#define DATA_CHANNEL_MAX_SESSION_DURATION_MS (120UL * 60UL * 1000UL)
#define DATA_CHANNEL_MAX_MESSAGE_SIZE 256

#define STREAM_CAMERA_FB_COUNT 3
#define STREAM_STATS_LOG_INTERVAL_MS 5000
#define STREAM_CAPTURE_READY_THRESHOLD_US 2000

#define DEVICE_COMMAND_VERSION 1

#define ServerHttpsPort 7010
#define ServerTcpPort 7000

#define DEBUG_ON false

#define DEBUG_PRINT(x)   \
  do                     \
  {                      \
    if (DEBUG_ON)        \
      Serial.println(x); \
  } while (0)
